#!/bin/bash

PARTITION=mko # teach coms sauer
NCPUS=1 # cores per job
NBATCH=690 # input per batch
EXTENSION=xyz # extension to pack
OUTEXT=optxyz # extenion to unpack
MEM=3GB

# Check ssh key is setup
ssh_pri=`ssh-keygen -y -f ~/.ssh/id_rsa`
ssh_pub=`cat ~/.ssh/id_rsa.pub`
if [[ $ssh_pub != $ssh_pri*  ]]; then

    echo
    echo "SSH key not setup. Please run 'ssh-keygen' in the terminal,"
    echo "to setup a key-pair (ssh with no password), before running this"
    echo "script"
    echo

    exit 4
fi

# note
#   #SBATCH -w, --nodelist=asusnode103

PWD=`pwd`
JOB=${PWD##*/}
SUBMIT=qsub.tmp
host=$HOSTNAME


files=`ls -f *$EXTENSION`

# Remove input files which is already done
out_files=`ls -f *$OUTEXT 2> /dev/null`

for x in $out_files; do
    inp=${x%.*}.$EXTENSION
    files=`echo $files | sed "s/$inp//"`
done

foo=( $files )
nfiles=`echo "$files" | wc -w`

#echo $files
#echo $nfiles

counter=0
while [  $counter -lt $nfiles  ]; do

    tarfile=batch_${counter}_xtb.tar.gz
    outfile=batch_${counter}_log_xtb.tar.gz

    tar -czf $tarfile ${foo[@]:$counter:$NBATCH}

    cjob=$JOB\_\_$counter

    cat > $SUBMIT <<!EOF
#!/bin/bash
#SBATCH --job-name=$cjob
#SBATCH --nodes=1
#SBATCH --cpus-per-task=$NCPUS
#SBATCH --ntasks=1
#SBATCH --error=$PWD/$cjob\_%j.stderr
#SBATCH --output=$PWD/$cjob\_%j.stdout
#SBATCH --time=100:00:00
#SBATCH --partition=$PARTITION
#SBATCH --no-requeue
#SBATCH --mem=$MEM


start=\`date +%s\`


nodename=\$HOSTNAME
echo 0 "Running on \$nodename"
echo 0 "un-tar input files"


mkdir /scratch/\$SLURM_JOB_ID
cd /scratch/\$SLURM_JOB_ID


cp $PWD/$tarfile .
tar -xzf $tarfile

export XTBHOME=/opt/xtb/6.1/xtb-190527/bin


ulimit -s unlimited
export OMP_STACKSIZE=$MEM
export OMP_NUM_THREADS=$NCPUS
export MPL_NUM_THREADS=$NCPUS

run_calculation () {

    input=\${1%.*}

    echo \$input

    mkdir \$input
    cp \$input.xyz \$input/\$input.xyz
    cd \$input

    /opt/xtb/6.1/xtb-190527/bin/xtb \$input.xyz --opt tight --gfn 2 > \$input.xtbout

    mv xtbopt.xyz ../\$input.optxyz
    #mv \$input.xtbout $PWD
    #cp \$input.xtbout ../
    cd ..

}

export -f run_calculation

# END MOPAC


end=\`date +%s\`
runtime=\$((end-start))
echo \$runtime "run calculation"


ls -f *.$EXTENSION | parallel -j$NCPUS "run_calculation {}"


end=\`date +%s\`
runtime=\$((end-start))
echo \$runtime "tar output"


tar -czf $outfile *.$OUTEXT
cp $outfile $PWD


end=\`date +%s\`
runtime=\$((end-start))
echo \$runtime "untar in $PWD"


ssh sunray "cd $PWD && tar xzf $outfile"


end=\`date +%s\`
runtime=\$((end-start))
echo \$runtime "done"


convertsecs() {
    ((h=\${1}/3600))
    ((m=(\${1}%3600)/60))
    ((s=\${1}%60))
    printf "%02d:%02d:%02d\n" \$h \$m \$s
}

convertsecs \$runtime

!EOF

    # submit batch
    sbatch $SUBMIT

    # next
    let counter+=$NBATCH

done



